dist: trusty
sudo: required

language: node_js
node_js:
    - "4"
    - "6"

jdk: oraclejdk8

notifications:
  irc:
    channels:
      - "irc.freenode.org#wikimedia-services"
    on_success: change
    on_failure: always

before_install:
  - wget https://archive.apache.org/dist/cassandra/2.2.6/apache-cassandra-2.2.6-bin.tar.gz -P ../
  - tar -xzf ../apache-cassandra-2.2.6-bin.tar.gz -C ../
  - sh ../apache-cassandra-2.2.6/bin/cassandra > /dev/null
  
addons:
  sonarqube:
    organization: "inverno-github"

script: sh test/utils/run_tests.sh coverage all && (npm run-script coveralls || exit 0)
script: sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'
